name: Build & Push Airflow Image

on:
  push:
    branches: [master]
    paths:
      - 'airflow/**'

jobs:
  build-airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./airflow
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/airflow:latest

      - name: Upload README to Docker Hub
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/airflow
          readme-filepath: ./airflow/README.md
          short-description: This custom Docker image extends the official Apache Airflow image with additional packages and functionality to enhance task execution and alerting.
